### ISSUE TITLE
New lobby colors

### ISSUE THREAD

**Issue by RoinujNosde** [GaborSuranyi/dbd-bloodpoint-spender#1]
The script sometimes gets stuck trying to click somewhere in that area

![image](https://user-images.githubusercontent.com/6441328/214171102-09270cac-1e03-4e9c-8f0e-c26182005667.png)

**Comment by gs-mancs** [comment]
Yeah noted it the other day.
I'll need to refine the search area, this new menu background has a very similar slice that the script looks for.

Thanks for being the first test user! ;-)

**Comment by gs-mancs** [comment]
@RoinujNosde new update is out, I've ran through a few common resolutions to find a more resonable, and more closely restricted search box, so that it won't wonder off with this new bright background.

Could you please take a look if this update resolves your issue?

Cheers!

**Comment by RoinujNosde** [comment]
Hi,
Thanks for the quick response!

It's getting stuck at this spot now:
![image](https://user-images.githubusercontent.com/6441328/214440447-0c8b2dc0-eddd-4239-be28-402bd6688b83.png)

**Comment by gs-mancs** [comment]
Hmm. Could you please let me know your exact desktop resolution, so I can reproduce this?
Also, not sure if UX scale matters for the menu, but let me know that as well.

**Comment by RoinujNosde** [comment]
The resolution is 2560 x 1080.
I will check the UX scale when I get home.

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/215146052-5cb598da-52b7-4df7-9d72-582486880281.png)

**Comment by gs-mancs** [comment]
Cheers, new version deployed.
Had a quick test on 2560x1080, latest version works fine for me.

Let me know how it goes.

**Comment by RoinujNosde** [comment]
Weird, it's still getting stuck at the [same place](https://github.com/GaborSuranyi/dbd-bloodpoint-spender/issues/1#issuecomment-1402802908).
